//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderFiles
    {
        public int FileId { get; set; }
        public int OrderNumber { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public int Version { get; set; }
        public string DocumentType { get; set; }
        public string XMLFilePath { get; set; }
        public string CreditStatus { get; set; }
        public string Description { get; set; }
    }
}
