//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OAMDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderComments
    {
        public int OrderCommentId { get; set; }
        public System.DateTime OrderCommentDate { get; set; }
        public string OrderComment { get; set; }
        public string OrderCommentUser { get; set; }
        public int OrderId { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
